// <auto-generated> by kotlin/clr
public static class AppKt
{
    public static void main()
    {
        var g = new Greeter("Visual Studio");
        System.Console.WriteLine(g.greet());
        var total = 0;
        var i = 1;
        while ((i <= 5))
        {
            total = (total + i);
            i = (i + 1);
        }
        System.Console.WriteLine(string.Concat("sum 1..5 = ", total));
    }
    
    public static void Main(string[] args)
    {
        main();
    }
}
