// <auto-generated> by kotlin/clr
public class Greeter
{
    public string name;
    public Greeter(string name)
    {
        this.name = name;
    }
    public string greet()
    {
        return string.Concat("Hello, ", this.name, ", from a .ktproj!");
    }
    
}

