<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>DotKt.Toolchain.nuspec</NuspecFile>
    <NuspecProperties>version=0.9.1+kotlin-2.2.0</NuspecProperties>
    <NoWarn>NU5128;NU5100</NoWarn>
  </PropertyGroup>
</Project>
