package clrc.backend

import org.jetbrains.kotlin.ir.declarations.IrAnnotationContainer
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrFile
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.declarations.IrVariable
import org.jetbrains.kotlin.ir.expressions.IrBlock
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrConst
import org.jetbrains.kotlin.ir.expressions.IrConstructorCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression
import org.jetbrains.kotlin.ir.expressions.IrFunctionExpression
import org.jetbrains.kotlin.ir.expressions.IrGetObjectValue
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.expressions.IrReturn
import org.jetbrains.kotlin.ir.expressions.IrSetValue
import org.jetbrains.kotlin.ir.expressions.IrStringConcatenation
import org.jetbrains.kotlin.ir.expressions.IrTypeOperator
import org.jetbrains.kotlin.ir.expressions.IrTypeOperatorCall
import org.jetbrains.kotlin.ir.expressions.IrWhen
import org.jetbrains.kotlin.ir.expressions.IrWhileLoop
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.IrTypeProjection
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.classifierOrNull
import org.jetbrains.kotlin.ir.types.isUnit
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI

/**
 * M0 codegen: walk raw Kotlin IR for one file and emit a single C# static class.
 *
 * Scope (deliberately small): top-level functions, primitive types, arithmetic/comparison,
 * if/when-as-expression, while, calls, string templates, and `println`. Everything is rendered
 * straight from the IR — no intermediate lowering — because the M0 subset maps 1:1 onto C#.
 *
 * `symbol.owner` access is safe here: we run after IR construction is fully complete.
 */
@OptIn(UnsafeDuringIrConstructionAPI::class)
class CSharpCodegen {

	private val sb = StringBuilder()
	private var indent = 0

	private fun line(text: String) {
		repeat(indent) { sb.append("    ") }
		sb.append(text).append('\n')
	}

	fun generateFile(file: IrFile): String {
		sb.setLength(0)
		indent = 0
		val className = fileClassName(file)
		val functions = file.declarations.filterIsInstance<IrSimpleFunction>()

		// Files that only declare `@Clr` façades / annotations produce no C# of their own.
		if (functions.isEmpty()) return ""

		line("// <auto-generated> by kotlin/clr (M0)")
		line("public static class $className")
		line("{")
		indent++
		for (function in functions) {
			generateFunction(function)
			line("")
		}
		// Synthesize the CLR entry point if this file declares `fun main`.
		functions.firstOrNull { it.name.asString() == "main" && it.parameters.none { p -> p.kind == IrParameterKind.Regular } }
			?.let {
				line("public static void Main(string[] args)")
				line("{")
				indent++
				line("main();")
				indent--
				line("}")
			}
		indent--
		line("}")
		return sb.toString()
	}

	private fun generateFunction(function: IrSimpleFunction) {
		val ret = csType(function.returnType)
		val params = function.parameters
			.filter { it.kind == IrParameterKind.Regular }
			.joinToString(", ") { "${csType(it.type)} ${it.name.asString()}" }
		line("public static $ret ${function.name.asString()}($params)")
		line("{")
		indent++
		when (val body = function.body) {
			is IrBlockBody -> body.statements.forEach { generateStatement(it) }
			else -> line("// unsupported body: ${body?.let { it::class.simpleName }}")
		}
		indent--
		line("}")
	}

	private fun generateStatement(stmt: org.jetbrains.kotlin.ir.IrElement) {
		when (stmt) {
			is IrVariable -> {
				// `var` lets C# infer the concrete (possibly .NET) type from the initializer.
				val init = stmt.initializer?.let { genExpr(it) }
				if (init != null) line("var ${stmt.name.asString()} = $init;")
				else line("${csType(stmt.type)} ${stmt.name.asString()};")
			}
			is IrSetValue -> line("${stmt.symbol.owner.name.asString()} = ${genExpr(stmt.value)};")
			is IrReturn -> {
				if (stmt.value.type.isUnit()) line("return;")
				else line("return ${genExpr(stmt.value)};")
			}
			is IrWhileLoop -> {
				line("while (${genExpr(stmt.condition)})")
				line("{")
				indent++
				(stmt.body as? IrBlock)?.statements?.forEach { generateStatement(it) }
					?: stmt.body?.let { generateStatement(it) }
				indent--
				line("}")
			}
			is IrWhen -> generateWhenStatement(stmt)
			is IrBlock -> stmt.statements.forEach { generateStatement(it) }
			is IrExpression -> line("${genExpr(stmt)};")
			else -> line("// unsupported statement: ${stmt::class.simpleName}")
		}
	}

	private fun generateWhenStatement(whenExpr: IrWhen) {
		whenExpr.branches.forEachIndexed { index, branch ->
			val isElse = branch.condition.let { it is IrConst && it.value == true }
			when {
				index == 0 -> line("if (${genExpr(branch.condition)})")
				isElse -> line("else")
				else -> line("else if (${genExpr(branch.condition)})")
			}
			line("{")
			indent++
			generateStatement(branch.result)
			indent--
			line("}")
		}
	}

	// ----- expressions -----

	private fun genExpr(expr: IrExpression): String = when (expr) {
		is IrConst -> constLiteral(expr)
		is IrGetValue -> expr.symbol.owner.name.asString()
		is IrStringConcatenation -> "string.Concat(${expr.arguments.joinToString(", ") { genExpr(it) }})"
		is IrWhen -> ternary(expr)
		is IrConstructorCall -> genConstructorCall(expr)
		is IrCall -> genCall(expr)
		is IrFunctionExpression -> renderLambda(expr)
		is IrGetObjectValue -> (clrName(expr.symbol.owner)?.let { "global::$it" }) ?: expr.symbol.owner.name.asString()
		is IrTypeOperatorCall -> genTypeOperator(expr)
		else -> "/* unsupported expr: ${expr::class.simpleName} */ default"
	}

	private fun genTypeOperator(expr: IrTypeOperatorCall): String = when (expr.operator) {
		IrTypeOperator.CAST, IrTypeOperator.SAFE_CAST ->
			"((${csType(expr.typeOperand)})${genExpr(expr.argument)})"
		// Implicit casts / coercions to Unit / notnull just pass the value through.
		else -> genExpr(expr.argument)
	}

	/** A Kotlin lambda becomes a C# lambda, which the CLR binds to the target delegate (e.g. Action). */
	private fun renderLambda(expr: IrFunctionExpression): String {
		val fn = expr.function
		val params = fn.parameters
			.filter { it.kind == IrParameterKind.Regular }
			.joinToString(", ") { it.name.asString() }
		val statements = (fn.body as? IrBlockBody)?.statements.orEmpty()
		val body = statements.joinToString(" ") { renderInline(it) }
		return "($params) => { $body }"
	}

	/** Single-line rendering of a statement, for use inside lambda bodies. */
	private fun renderInline(stmt: org.jetbrains.kotlin.ir.IrElement): String = when (stmt) {
		is IrVariable -> stmt.initializer?.let { "var ${stmt.name.asString()} = ${genExpr(it)};" } ?: "${csType(stmt.type)} ${stmt.name.asString()};"
		is IrSetValue -> "${stmt.symbol.owner.name.asString()} = ${genExpr(stmt.value)};"
		is IrReturn -> if (stmt.value.type.isUnit()) "return;" else "return ${genExpr(stmt.value)};"
		is IrExpression -> "${genExpr(stmt)};"
		else -> "/* unsupported inline stmt: ${stmt::class.simpleName} */"
	}

	private fun ternary(whenExpr: IrWhen): String {
		// Fold branches right-to-left into nested conditional expressions.
		var result = "default"
		for (branch in whenExpr.branches.asReversed()) {
			val isElse = branch.condition.let { it is IrConst && it.value == true }
			result = if (isElse) genExpr(branch.result)
			else "(${genExpr(branch.condition)} ? ${genExpr(branch.result)} : $result)"
		}
		return result
	}

	private fun genCall(call: IrCall): String {
		val callee = call.symbol.owner
		val name = callee.name.asString()
		val clrType = (callee.parent as? IrClass)?.let { clrName(it) }

		// Indexer: `list[i]` / `list[i] = v` on a @Clr type -> C# indexer syntax.
		if (clrType != null && callee.isOperator && (name == "get" || name == "set")) {
			val target = memberTarget(call, clrType)
			val args = regularArgs(call)
			return if (name == "get") "$target[${args.joinToString(", ") { genExpr(it) }}]"
			else "$target[${args.dropLast(1).joinToString(", ") { genExpr(it) }}] = ${genExpr(args.last())}"
		}

		// Property get/set on a @Clr type -> C# property access.
		val property = callee.correspondingPropertySymbol?.owner
		if (clrType != null && property != null) {
			val propName = clrName(property) ?: property.name.asString()
			val target = memberTarget(call, clrType)
			return if (callee === property.setter) "$target.$propName = ${genExpr(regularArgs(call).first())}"
			else "$target.$propName"
		}

		// Method on a @Clr type -> static (object/companion) or instance (receiver.Member) call.
		if (clrType != null) {
			val member = clrName(callee) ?: name
			val args = regularArgs(call).joinToString(", ") { genExpr(it) }
			return "${memberTarget(call, clrType)}.$member($args)"
		}

		val operands = operandList(call)
		BINARY_OPERATORS[name]?.let { op ->
			if (operands.size == 2) return "(${genExpr(operands[0])} $op ${genExpr(operands[1])})"
		}
		UNARY_OPERATORS[name]?.let { op ->
			if (operands.size == 1) return "($op${genExpr(operands[0])})"
		}

		val fqName = callee.fqNameOrNull()
		if (fqName == "kotlin.io.println") return "System.Console.WriteLine(${operands.joinToString(", ") { genExpr(it) }})"
		if (fqName == "kotlin.io.print") return "System.Console.Write(${operands.joinToString(", ") { genExpr(it) }})"

		// Default: a call to a sibling top-level function (same C# static class).
		return "$name(${operands.joinToString(", ") { genExpr(it) }})"
	}

	private fun genConstructorCall(call: IrConstructorCall): String {
		val klass = call.symbol.owner.parent as? IrClass
		val clrType = klass?.let { clrName(it) }
		val args = regularArgs(call).joinToString(", ") { genExpr(it) }
		val typeName = clrType?.let { "global::$it${csTypeArgs(call.type)}" } ?: klass?.name?.asString() ?: "object"
		return "new $typeName($args)"
	}

	/** Renders C# generic type arguments, e.g. `<int, string>`, from a parameterized type. */
	private fun csTypeArgs(type: IrType): String {
		val args = (type as? IrSimpleType)?.arguments.orEmpty()
		if (args.isEmpty()) return ""
		return "<" + args.joinToString(", ") { (it as? IrTypeProjection)?.type?.let(::csType) ?: "object" } + ">"
	}

	/** The C# call target: a static `global::Type`, or the instance receiver expression. */
	private fun memberTarget(call: IrFunctionAccessExpression, clrType: String): String {
		val receiver = dispatchReceiverOf(call)
		return if (receiver != null && receiver !is IrGetObjectValue) genExpr(receiver) else "global::$clrType"
	}

	private fun dispatchReceiverOf(call: IrFunctionAccessExpression): IrExpression? {
		val params = (call.symbol.owner as? IrFunction)?.parameters ?: return null
		val idx = params.indexOfFirst { it.kind == IrParameterKind.DispatchReceiver }
		return if (idx in 0 until call.arguments.size) call.arguments[idx] else null
	}

	/** Operands corresponding to `Regular` parameters only (drops dispatch/extension receivers). */
	private fun regularArgs(call: IrFunctionAccessExpression): List<IrExpression> {
		val params = (call.symbol.owner as? IrFunction)?.parameters ?: emptyList()
		return call.arguments.mapIndexedNotNull { i, arg ->
			if (arg != null && i < params.size && params[i].kind == IrParameterKind.Regular) arg else null
		}
	}

	/** Reads the `.NET` name from a `@Clr("...")` annotation, if present. */
	private fun clrName(decl: IrAnnotationContainer): String? {
		for (annotation in decl.annotations) {
			if ((annotation as? IrConstructorCall)?.type?.classFqName?.asString() == CLR_ANNOTATION) {
				return (annotation.arguments.firstOrNull() as? IrConst)?.value as? String
			}
		}
		return null
	}

	// New (2.2+) argument model: `arguments` is aligned to the callee's parameter list, with the
	// dispatch/extension receiver occupying the leading slots. filterNotNull drops absent defaults.
	private fun operandList(call: IrFunctionAccessExpression): List<IrExpression> =
		call.arguments.filterNotNull()

	private fun constLiteral(const: IrConst): String = when (val v = const.value) {
		is String -> "\"" + v.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""
		is Boolean -> v.toString()
		is Char -> "'$v'"
		is Long -> "${v}L"
		null -> "null"
		else -> v.toString()
	}

	private fun csType(type: IrType): String {
		// A @Clr façade type maps to its real .NET type (with generic arguments, if any).
		(type.classifierOrNull?.owner as? IrClass)?.let { clrName(it) }?.let { return "global::$it${csTypeArgs(type)}" }
		return when (type.classFqName?.asString()) {
			"kotlin.Unit", "kotlin.Nothing" -> "void"
		"kotlin.Int" -> "int"
		"kotlin.Long" -> "long"
		"kotlin.Short" -> "short"
		"kotlin.Byte" -> "sbyte"
		"kotlin.Double" -> "double"
		"kotlin.Float" -> "float"
		"kotlin.Boolean" -> "bool"
		"kotlin.Char" -> "char"
		"kotlin.String" -> "string"
		"kotlin.Any" -> "object"
			else -> "object"
		}
	}

	private fun fileClassName(file: IrFile): String {
		val base = file.fileEntry.name.substringAfterLast('/').substringAfterLast('\\').removeSuffix(".kt")
		return base.replaceFirstChar { it.uppercaseChar() } + "Kt"
	}

	companion object {
		private const val CLR_ANNOTATION = "clr.Clr"

		private val BINARY_OPERATORS = mapOf(
			"plus" to "+", "minus" to "-", "times" to "*", "div" to "/", "rem" to "%",
			"less" to "<", "lessOrEqual" to "<=", "greater" to ">", "greaterOrEqual" to ">=",
			"EQEQ" to "==", "EQEQEQ" to "==", "ieee754equals" to "==",
		)

		private val UNARY_OPERATORS = mapOf(
			"unaryMinus" to "-", "unaryPlus" to "+", "not" to "!",
		)
	}
}

private fun org.jetbrains.kotlin.ir.declarations.IrDeclaration.fqNameOrNull(): String? =
	(this as? IrSimpleFunction)?.let { fn ->
		val parent = fn.parent
		val parentFq = (parent as? org.jetbrains.kotlin.ir.declarations.IrPackageFragment)?.packageFqName?.asString()
		if (parentFq != null) "$parentFq.${fn.name.asString()}" else null
	}
