package clrc.backend

import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.ir.declarations.IrAnonymousInitializer
import org.jetbrains.kotlin.ir.declarations.IrAnnotationContainer
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrConstructor
import org.jetbrains.kotlin.ir.declarations.IrEnumEntry
import org.jetbrains.kotlin.ir.declarations.IrFile
import org.jetbrains.kotlin.ir.declarations.IrPackageFragment
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.declarations.IrVariable
import org.jetbrains.kotlin.ir.expressions.IrBlock
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrConst
import org.jetbrains.kotlin.ir.expressions.IrConstructorCall
import org.jetbrains.kotlin.ir.expressions.IrDelegatingConstructorCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrExpressionBody
import org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression
import org.jetbrains.kotlin.ir.expressions.IrFunctionExpression
import org.jetbrains.kotlin.ir.expressions.IrGetEnumValue
import org.jetbrains.kotlin.ir.expressions.IrGetField
import org.jetbrains.kotlin.ir.expressions.IrGetObjectValue
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.expressions.IrInstanceInitializerCall
import org.jetbrains.kotlin.ir.expressions.IrReturn
import org.jetbrains.kotlin.ir.expressions.IrSetField
import org.jetbrains.kotlin.ir.expressions.IrSetValue
import org.jetbrains.kotlin.ir.expressions.IrStringConcatenation
import org.jetbrains.kotlin.ir.expressions.IrThrow
import org.jetbrains.kotlin.ir.expressions.IrTry
import org.jetbrains.kotlin.ir.expressions.IrTypeOperator
import org.jetbrains.kotlin.ir.expressions.IrTypeOperatorCall
import org.jetbrains.kotlin.ir.expressions.IrWhen
import org.jetbrains.kotlin.ir.expressions.IrWhileLoop
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.IrTypeProjection
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.classifierOrNull
import org.jetbrains.kotlin.ir.types.isUnit
import org.jetbrains.kotlin.ir.util.fqNameWhenAvailable
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI

/**
 * M0 codegen: walk raw Kotlin IR for one file and emit a single C# static class.
 *
 * Scope (deliberately small): top-level functions, primitive types, arithmetic/comparison,
 * if/when-as-expression, while, calls, string templates, and `println`. Everything is rendered
 * straight from the IR — no intermediate lowering — because the M0 subset maps 1:1 onto C#.
 *
 * `symbol.owner` access is safe here: we run after IR construction is fully complete.
 */
@OptIn(UnsafeDuringIrConstructionAPI::class)
class CSharpCodegen {

	private val sb = StringBuilder()
	private var indent = 0

	// Inline substitutions for synthetic temporaries (e.g. a `when` subject) used in expression position.
	private val valSubst = HashMap<String, String>()

	private fun line(text: String) {
		repeat(indent) { sb.append("    ") }
		sb.append(text).append('\n')
	}

	fun generateFile(file: IrFile): String {
		sb.setLength(0)
		indent = 0
		// User-declared types (not @Clr façades, not annotations) become C# types.
		val userTypes = file.declarations.filterIsInstance<IrClass>().filter { clrName(it) == null }
		val classes = userTypes.filter { it.kind == ClassKind.CLASS }
		val objects = userTypes.filter { it.kind == ClassKind.OBJECT && !it.isCompanion }
		val interfaces = userTypes.filter { it.kind == ClassKind.INTERFACE }
		val enums = userTypes.filter { it.kind == ClassKind.ENUM_CLASS }
		val functions = file.declarations.filterIsInstance<IrSimpleFunction>()

		if (userTypes.isEmpty() && functions.isEmpty()) return ""

		line("// <auto-generated> by kotlin/clr")
		for (e in enums) { generateEnum(e); line("") }
		for (i in interfaces) { generateInterface(i); line("") }
		for (klass in classes) { generateClass(klass); line("") }
		for (obj in objects) { generateObject(obj); line("") }

		if (functions.isNotEmpty()) {
			line("public static class ${fileClassName(file)}")
			line("{")
			indent++
			for (function in functions) { generateFunction(function, static = true); line("") }
			functions.firstOrNull { it.name.asString() == "main" && it.parameters.none { p -> p.kind == IrParameterKind.Regular } }
				?.let {
					line("public static void Main(string[] args)")
					line("{")
					indent++
					line("main();")
					indent--
					line("}")
				}
			indent--
			line("}")
		}
		return sb.toString()
	}

	private fun generateInterface(iface: IrClass) {
		line("public interface ${iface.name.asString()}${superList(iface)}")
		line("{")
		indent++
		for (m in iface.memberMethods(requireBody = false)) {
			val params = m.parameters.filter { it.kind == IrParameterKind.Regular }
				.joinToString(", ") { "${csType(it.type)} ${csId(it.name.asString())}" }
			line("${csType(m.returnType)} ${m.name.asString()}($params);")
		}
		indent--
		line("}")
	}

	private fun generateEnum(enum: IrClass) {
		val entries = enum.declarations.filterIsInstance<IrEnumEntry>().joinToString(", ") { it.name.asString() }
		line("public enum ${enum.name.asString()}")
		line("{")
		indent++
		line(entries)
		indent--
		line("}")
	}

	private fun generateClass(klass: IrClass) {
		val abstract = if (klass.modality == Modality.ABSTRACT) "abstract " else ""
		line("public ${abstract}class ${klass.name.asString()}${superList(klass)}")
		line("{")
		indent++
		for (prop in klass.memberProperties()) generateMemberProperty(prop)
		for (ctor in klass.declarations.filterIsInstance<IrConstructor>()) generateConstructor(klass, ctor)
		for (m in klass.memberMethods()) { generateFunction(m, static = false); line("") }
		indent--
		line("}")
	}

	private fun generateObject(obj: IrClass) {
		// A Kotlin `object` -> sealed C# class with an INSTANCE singleton.
		line("public sealed class ${obj.name.asString()}")
		line("{")
		indent++
		line("public static readonly ${obj.name.asString()} INSTANCE = new ${obj.name.asString()}();")
		for (prop in obj.memberProperties()) generateMemberProperty(prop)
		for (m in obj.memberMethods()) { generateFunction(m, static = false); line("") }
		indent--
		line("}")
	}

	// Real (non-inherited, non-synthetic) members to emit. Fake overrides come from C# inheritance.
	private fun IrClass.memberProperties(): List<IrProperty> =
		declarations.filterIsInstance<IrProperty>().filter { !it.isFakeOverride }

	private fun IrClass.memberMethods(requireBody: Boolean = true): List<IrSimpleFunction> =
		declarations.filterIsInstance<IrSimpleFunction>()
			.filter { it.correspondingPropertySymbol == null && !it.isFakeOverride && (!requireBody || it.body != null) }

	/** Backing-field property -> C# field; computed property -> C# property with a getter body. */
	private fun generateMemberProperty(prop: IrProperty) {
		val backing = prop.backingField
		if (backing != null) {
			line("public ${csType(backing.type)} ${csId(prop.name.asString())};")
		} else {
			val getter = prop.getter ?: return
			val body = (getter.body as? IrBlockBody)?.statements.orEmpty().joinToString(" ") { renderInline(it) }
			line("public ${csType(getter.returnType)} ${csId(prop.name.asString())} { get { $body } }")
		}
	}

	private fun generateConstructor(klass: IrClass, ctor: IrConstructor) {
		val params = ctor.parameters
			.filter { it.kind == IrParameterKind.Regular }
			.joinToString(", ") { "${csType(it.type)} ${csId(it.name.asString())}" }
		val body = ctor.body as? IrBlockBody
		val delegating = body?.statements?.filterIsInstance<IrDelegatingConstructorCall>()?.firstOrNull()
		val baseClause = delegating?.let { d ->
			val targetFq = (d.symbol.owner.parent as? IrClass)?.fqNameWhenAvailable?.asString()
			val baseArgs = regularArgs(d)
			if (targetFq != "kotlin.Any" && baseArgs.isNotEmpty())
				" : base(${baseArgs.joinToString(", ") { genExpr(it) }})"
			else ""
		} ?: ""
		line("public ${klass.name.asString()}($params)$baseClause")
		line("{")
		indent++
		body?.statements?.forEach { stmt ->
			when (stmt) {
				is IrDelegatingConstructorCall -> {} // handled in the base clause
				is IrInstanceInitializerCall -> emitInstanceInit(klass)
				else -> generateStatement(stmt)
			}
		}
		indent--
		line("}")
	}

	/** Expands field initializers and `init { }` blocks (normally an InitializersLowering job). */
	private fun emitInstanceInit(klass: IrClass) {
		for (decl in klass.declarations) {
			when (decl) {
				is IrProperty -> decl.backingField?.initializer?.let { init ->
					line("this.${decl.name.asString()} = ${genExpr((init as IrExpressionBody).expression)};")
				}
				is IrAnonymousInitializer -> (decl.body as? IrBlockBody)?.statements?.forEach { generateStatement(it) }
				else -> {}
			}
		}
	}

	private fun generateFunction(function: IrSimpleFunction, static: Boolean) {
		val ret = csType(function.returnType)
		val params = function.parameters
			.filter { it.kind == IrParameterKind.Regular }
			.joinToString(", ") { "${csType(it.type)} ${csId(it.name.asString())}" }
		// `override` only when overriding a class virtual; interface impls and open methods are virtual.
		val overridesClass = function.overriddenSymbols.any {
			(it.owner.parent as? IrClass)?.kind == ClassKind.CLASS
		}
		val modifier = when {
			static -> "static "
			overridesClass -> "override "
			function.modality == Modality.OPEN || function.modality == Modality.ABSTRACT -> "virtual "
			else -> ""
		}
		line("public $modifier$ret ${function.name.asString()}($params)")
		line("{")
		indent++
		when (val body = function.body) {
			is IrBlockBody -> body.statements.forEach { generateStatement(it) }
			else -> line("// unsupported body: ${body?.let { it::class.simpleName }}")
		}
		indent--
		line("}")
	}

	/** ` : Base, IFace1, IFace2` — base class first (C# requires it), then interfaces. */
	private fun superList(klass: IrClass): String {
		val supers = klass.superTypes
			.mapNotNull { it.classifierOrNull?.owner as? IrClass }
			.filter { it.fqNameWhenAvailable?.asString() != "kotlin.Any" && (it.kind == ClassKind.CLASS || it.kind == ClassKind.INTERFACE) }
			.sortedBy { if (it.kind == ClassKind.CLASS) 0 else 1 }
		if (supers.isEmpty()) return ""
		return " : " + supers.joinToString(", ") { clrName(it)?.let { n -> "global::$n" } ?: it.name.asString() }
	}

	private fun generateStatement(stmt: org.jetbrains.kotlin.ir.IrElement) {
		when (stmt) {
			is IrVariable -> {
				// `var` lets C# infer the concrete (possibly .NET) type from the initializer.
				val init = stmt.initializer?.let { genExpr(it) }
				if (init != null) line("var ${csId(stmt.name.asString())} = $init;")
				else line("${csType(stmt.type)} ${csId(stmt.name.asString())};")
			}
			is IrSetValue -> line("${valueName(stmt.symbol.owner.name.asString())} = ${genExpr(stmt.value)};")
			is IrSetField -> line("${stmt.receiver?.let { genExpr(it) } ?: "this"}.${csId(stmt.symbol.owner.name.asString())} = ${genExpr(stmt.value)};")
			is IrReturn -> {
				if (stmt.value.type.isUnit()) line("return;")
				else line("return ${genExpr(stmt.value)};")
			}
			is IrWhileLoop -> {
				line("while (${genExpr(stmt.condition)})")
				line("{")
				indent++
				(stmt.body as? IrBlock)?.statements?.forEach { generateStatement(it) }
					?: stmt.body?.let { generateStatement(it) }
				indent--
				line("}")
			}
			is IrWhen -> generateWhenStatement(stmt)
			is IrTry -> generateTry(stmt)
			is IrBlock -> if (stmt.origin?.toString() == "FOR_LOOP") generateForLoop(stmt)
			else stmt.statements.forEach { generateStatement(it) }
			is IrExpression -> line("${genExpr(stmt)};")
			else -> line("// unsupported statement: ${stmt::class.simpleName}")
		}
	}

	private fun generateWhenStatement(whenExpr: IrWhen) {
		whenExpr.branches.forEachIndexed { index, branch ->
			val isElse = branch.condition.let { it is IrConst && it.value == true }
			when {
				index == 0 -> line("if (${genExpr(branch.condition)})")
				isElse -> line("else")
				else -> line("else if (${genExpr(branch.condition)})")
			}
			line("{")
			indent++
			generateStatement(branch.result)
			indent--
			line("}")
		}
	}

	private fun generateTry(tryExpr: IrTry) {
		line("try")
		line("{")
		indent++
		emitBlockOrStatement(tryExpr.tryResult)
		indent--
		line("}")
		for (catch in tryExpr.catches) {
			val p = catch.catchParameter
			line("catch (${csType(p.type)} ${p.name.asString()})")
			line("{")
			indent++
			emitBlockOrStatement(catch.result)
			indent--
			line("}")
		}
		tryExpr.finallyExpression?.let {
			line("finally")
			line("{")
			indent++
			emitBlockOrStatement(it)
			indent--
			line("}")
		}
	}

	private fun emitBlockOrStatement(expr: IrExpression) {
		if (expr is IrBlock) expr.statements.forEach { generateStatement(it) } else generateStatement(expr)
	}

	/** A Kotlin `for (x in ...)` is desugared to iterator+while; re-fold it into a C# for/foreach. */
	private fun generateForLoop(block: IrBlock) {
		val iterVar = block.statements.getOrNull(0) as? IrVariable
		val whileLoop = block.statements.getOrNull(1) as? IrWhileLoop
		val bodyBlock = whileLoop?.body as? IrBlock
		val loopVar = bodyBlock?.statements?.getOrNull(0) as? IrVariable
		if (iterVar == null || bodyBlock == null || loopVar == null) {
			block.statements.forEach { generateStatement(it) }
			return
		}
		val loopName = loopVar.name.asString()
		val realBody = bodyBlock.statements.drop(1)
		// The iterable is the receiver of `.iterator()`.
		val source = (iterVar.initializer as? IrCall)?.let { dispatchReceiverOf(it) }
		val header = (source as? IrCall)?.let { rangeForHeader(loopName, it) }
			?: "foreach (var $loopName in ${source?.let { genExpr(it) } ?: "default"})"
		line(header)
		line("{")
		indent++
		realBody.forEach { generateStatement(it) }
		indent--
		line("}")
	}

	/** A C# `for` header for a Kotlin range (`a..b`, `a until b`, `a downTo b`), or null. */
	private fun rangeForHeader(name: String, range: IrCall): String? {
		val ops = operandList(range)
		if (ops.size != 2) return null
		val a = genExpr(ops[0]); val b = genExpr(ops[1])
		return when (range.symbol.owner.name.asString()) {
			"rangeTo" -> "for (int $name = $a; $name <= $b; $name++)"
			"until", "rangeUntil" -> "for (int $name = $a; $name < $b; $name++)"
			"downTo" -> "for (int $name = $a; $name >= $b; $name--)"
			else -> null
		}
	}

	// ----- expressions -----

	private fun genExpr(expr: IrExpression): String = when (expr) {
		is IrConst -> constLiteral(expr)
		is IrGetValue -> valSubst[expr.symbol.owner.name.asString()] ?: valueName(expr.symbol.owner.name.asString())
		is IrThrow -> "throw ${genExpr(expr.value)}"
		is IrBlock -> genBlockExpr(expr)
		is IrGetField -> "${expr.receiver?.let { genExpr(it) } ?: "this"}.${csId(expr.symbol.owner.name.asString())}"
		is IrStringConcatenation -> "string.Concat(${expr.arguments.joinToString(", ") { genExpr(it) }})"
		is IrWhen -> ternary(expr)
		is IrConstructorCall -> genConstructorCall(expr)
		is IrCall -> genCall(expr)
		is IrFunctionExpression -> renderLambda(expr)
		is IrGetObjectValue -> clrName(expr.symbol.owner)?.let { "global::$it" } ?: "${expr.symbol.owner.name.asString()}.INSTANCE"
		is IrGetEnumValue -> "${csType(expr.type)}.${expr.symbol.owner.name.asString()}"
		is IrTypeOperatorCall -> genTypeOperator(expr)
		else -> "/* unsupported expr: ${expr::class.simpleName} */ default"
	}

	private fun genTypeOperator(expr: IrTypeOperatorCall): String = when (expr.operator) {
		IrTypeOperator.CAST, IrTypeOperator.SAFE_CAST ->
			"((${csType(expr.typeOperand)})${genExpr(expr.argument)})"
		// Implicit casts / coercions to Unit / notnull just pass the value through.
		else -> genExpr(expr.argument)
	}

	/** A Kotlin lambda becomes a C# lambda, which the CLR binds to the target delegate (e.g. Action). */
	private fun renderLambda(expr: IrFunctionExpression): String {
		val fn = expr.function
		val params = fn.parameters
			.filter { it.kind == IrParameterKind.Regular }
			.joinToString(", ") { csId(it.name.asString()) }
		val statements = (fn.body as? IrBlockBody)?.statements.orEmpty()
		val body = statements.joinToString(" ") { renderInline(it) }
		return "($params) => { $body }"
	}

	/** Single-line rendering of a statement, for use inside lambda bodies. */
	private fun renderInline(stmt: org.jetbrains.kotlin.ir.IrElement): String = when (stmt) {
		is IrVariable -> stmt.initializer?.let { "var ${csId(stmt.name.asString())} = ${genExpr(it)};" } ?: "${csType(stmt.type)} ${csId(stmt.name.asString())};"
		is IrSetValue -> "${valueName(stmt.symbol.owner.name.asString())} = ${genExpr(stmt.value)};"
		is IrSetField -> "${stmt.receiver?.let { genExpr(it) } ?: "this"}.${csId(stmt.symbol.owner.name.asString())} = ${genExpr(stmt.value)};"
		is IrReturn -> if (stmt.value.type.isUnit()) "return;" else "return ${genExpr(stmt.value)};"
		is IrExpression -> "${genExpr(stmt)};"
		else -> "/* unsupported inline stmt: ${stmt::class.simpleName} */"
	}

	/** A block in expression position: a `when (subject)` lowers to `{ val tmp = subject; WHEN }`. */
	private fun genBlockExpr(block: IrBlock): String {
		val tmp = block.statements.getOrNull(0) as? IrVariable
		val whenExpr = block.statements.getOrNull(1) as? IrWhen
		if (block.statements.size == 2 && tmp != null && whenExpr != null && tmp.initializer != null) {
			val key = tmp.name.asString()
			valSubst[key] = "(${genExpr(tmp.initializer!!)})"
			val result = ternary(whenExpr)
			valSubst.remove(key)
			return result
		}
		// Generic block-expression: value is the last statement.
		return (block.statements.lastOrNull() as? IrExpression)?.let { genExpr(it) } ?: "default"
	}

	private fun ternary(whenExpr: IrWhen): String {
		// Fold branches right-to-left into nested conditional expressions.
		var result = "default"
		for (branch in whenExpr.branches.asReversed()) {
			val isElse = branch.condition.let { it is IrConst && it.value == true }
			result = if (isElse) genExpr(branch.result)
			else "(${genExpr(branch.condition)} ? ${genExpr(branch.result)} : $result)"
		}
		return result
	}

	private fun genCall(call: IrCall): String {
		val callee = call.symbol.owner
		val name = callee.name.asString()
		val declaringClass = callee.parent as? IrClass
		val clrType = declaringClass?.let { clrName(it) }
		val declFq = declaringClass?.fqNameWhenAvailable?.asString()
			?: (callee.parent as? IrPackageFragment)?.packageFqName?.asString()
		val isBuiltin = declFq == null || declFq.startsWith("kotlin")

		// Indexer: `list[i]` / `list[i] = v` on a @Clr type -> C# indexer syntax.
		if (clrType != null && callee.isOperator && (name == "get" || name == "set")) {
			val target = memberTarget(call, clrType)
			val args = regularArgs(call)
			return if (name == "get") "$target[${args.joinToString(", ") { genExpr(it) }}]"
			else "$target[${args.dropLast(1).joinToString(", ") { genExpr(it) }}] = ${genExpr(args.last())}"
		}

		// Property get/set (both @Clr and user classes) -> C# property access.
		val property = callee.correspondingPropertySymbol?.owner
		if (property != null) {
			val propName = clrName(property) ?: property.name.asString()
			val target = memberTarget(call, clrType ?: "")
			return if (callee === property.setter) "$target.$propName = ${genExpr(regularArgs(call).first())}"
			else "$target.$propName"
		}

		// Range membership: `x in a..b` -> `(x >= a && x <op> b)`.
		if (isBuiltin && name == "contains") {
			val range = dispatchReceiverOf(call) as? IrCall
			val value = regularArgs(call).firstOrNull()
			if (range != null && value != null) rangeForHeader("_", range)?.let {
				val ops = operandList(range)
				val op = if (range.symbol.owner.name.asString() == "rangeTo") "<=" else "<"
				return "(${genExpr(value)} >= ${genExpr(ops[0])} && ${genExpr(value)} $op ${genExpr(ops[1])})"
			}
		}

		// Built-in operators on primitives/intrinsics (NOT user methods that happen to be named `plus`).
		if (isBuiltin) {
			val operands = operandList(call)
			BINARY_OPERATORS[name]?.let { op ->
				if (operands.size == 2) return "(${genExpr(operands[0])} $op ${genExpr(operands[1])})"
			}
			UNARY_OPERATORS[name]?.let { op ->
				if (operands.size == 1) return "($op${genExpr(operands[0])})"
			}
			val fqName = callee.fqNameOrNull()
			if (fqName == "kotlin.io.println") return "System.Console.WriteLine(${regularArgs(call).joinToString(", ") { genExpr(it) }})"
			if (fqName == "kotlin.io.print") return "System.Console.Write(${regularArgs(call).joinToString(", ") { genExpr(it) }})"
		}

		// Method on a @Clr type -> static (object/companion) or instance (receiver.Member) call.
		if (clrType != null) {
			val member = clrName(callee) ?: name
			val args = regularArgs(call).joinToString(", ") { genExpr(it) }
			return "${memberTarget(call, clrType)}.$member($args)"
		}

		// User-declared call: instance method (`recv.m(...)`) or sibling top-level (`m(...)`).
		val receiver = dispatchReceiverOf(call)
		val args = regularArgs(call).joinToString(", ") { genExpr(it) }
		return if (receiver != null && receiver !is IrGetObjectValue) "${genExpr(receiver)}.$name($args)"
		else "$name($args)"
	}

	private fun genConstructorCall(call: IrConstructorCall): String {
		val klass = call.symbol.owner.parent as? IrClass
		val clrType = klass?.let { clrName(it) }
		val args = regularArgs(call).joinToString(", ") { genExpr(it) }
		val typeName = clrType?.let { "global::$it${csTypeArgs(call.type)}" } ?: klass?.name?.asString() ?: "object"
		return "new $typeName($args)"
	}

	/** Renders C# generic type arguments, e.g. `<int, string>`, from a parameterized type. */
	private fun csTypeArgs(type: IrType): String {
		val args = (type as? IrSimpleType)?.arguments.orEmpty()
		if (args.isEmpty()) return ""
		return "<" + args.joinToString(", ") { (it as? IrTypeProjection)?.type?.let(::csType) ?: "object" } + ">"
	}

	/** The C# call target: the instance receiver expression, or a static `global::Type`. */
	private fun memberTarget(call: IrFunctionAccessExpression, clrType: String): String {
		val receiver = dispatchReceiverOf(call)
		return when {
			receiver != null && receiver !is IrGetObjectValue -> genExpr(receiver)
			clrType.isNotEmpty() -> "global::$clrType"
			receiver is IrGetObjectValue -> genExpr(receiver) // user object singleton -> Name.INSTANCE
			else -> "this"
		}
	}

	/** The Kotlin synthetic dispatch-receiver name `<this>` becomes C# `this`. */
	private fun valueName(name: String): String = if (name == "<this>") "this" else csId(name)

	/** Escapes a Kotlin identifier that collides with a C# keyword (`out` -> `@out`). */
	private fun csId(name: String): String = if (name in CS_KEYWORDS) "@$name" else name

	private fun dispatchReceiverOf(call: IrFunctionAccessExpression): IrExpression? {
		val params = (call.symbol.owner as? IrFunction)?.parameters ?: return null
		val idx = params.indexOfFirst { it.kind == IrParameterKind.DispatchReceiver }
		return if (idx in 0 until call.arguments.size) call.arguments[idx] else null
	}

	/** Operands corresponding to `Regular` parameters only (drops dispatch/extension receivers). */
	private fun regularArgs(call: IrFunctionAccessExpression): List<IrExpression> {
		val params = (call.symbol.owner as? IrFunction)?.parameters ?: emptyList()
		return call.arguments.mapIndexedNotNull { i, arg ->
			if (arg != null && i < params.size && params[i].kind == IrParameterKind.Regular) arg else null
		}
	}

	/** Reads the `.NET` name from a `@Clr("...")` annotation, if present. */
	private fun clrName(decl: IrAnnotationContainer): String? {
		for (annotation in decl.annotations) {
			if ((annotation as? IrConstructorCall)?.type?.classFqName?.asString() == CLR_ANNOTATION) {
				return (annotation.arguments.firstOrNull() as? IrConst)?.value as? String
			}
		}
		return null
	}

	// New (2.2+) argument model: `arguments` is aligned to the callee's parameter list, with the
	// dispatch/extension receiver occupying the leading slots. filterNotNull drops absent defaults.
	private fun operandList(call: IrFunctionAccessExpression): List<IrExpression> =
		call.arguments.filterNotNull()

	private fun constLiteral(const: IrConst): String = when (val v = const.value) {
		is String -> "\"" + v.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + "\""
		is Boolean -> v.toString()
		is Char -> "'$v'"
		is Long -> "${v}L"
		null -> "null"
		else -> v.toString()
	}

	private fun csType(type: IrType): String {
		val fq = type.classFqName?.asString()
		// Primitives & well-known Kotlin types map to C# keywords first.
		PRIMITIVES[fq]?.let { return it }
		// Kotlin/JVM types (exceptions etc.) map to their .NET equivalents.
		NET_TYPES[fq]?.let { return "global::$it" }
		val klass = type.classifierOrNull?.owner as? IrClass
		if (klass != null) {
			// @Clr façade -> real .NET type; otherwise a user-declared class/object/interface.
			clrName(klass)?.let { return "global::$it${csTypeArgs(type)}" }
			return klass.name.asString() + csTypeArgs(type)
		}
		return "object"
	}

	private fun fileClassName(file: IrFile): String {
		val base = file.fileEntry.name.substringAfterLast('/').substringAfterLast('\\').removeSuffix(".kt")
		return base.replaceFirstChar { it.uppercaseChar() } + "Kt"
	}

	companion object {
		private const val CLR_ANNOTATION = "clr.Clr"

		private val BINARY_OPERATORS = mapOf(
			"plus" to "+", "minus" to "-", "times" to "*", "div" to "/", "rem" to "%",
			"less" to "<", "lessOrEqual" to "<=", "greater" to ">", "greaterOrEqual" to ">=",
			"EQEQ" to "==", "EQEQEQ" to "==", "ieee754equals" to "==",
		)

		private val UNARY_OPERATORS = mapOf(
			"unaryMinus" to "-", "unaryPlus" to "+", "not" to "!",
		)

		private val PRIMITIVES = mapOf(
			"kotlin.Unit" to "void", "kotlin.Nothing" to "void",
			"kotlin.Int" to "int", "kotlin.Long" to "long", "kotlin.Short" to "short",
			"kotlin.Byte" to "sbyte", "kotlin.Double" to "double", "kotlin.Float" to "float",
			"kotlin.Boolean" to "bool", "kotlin.Char" to "char", "kotlin.String" to "string",
			"kotlin.Any" to "object",
		)

		private val CS_KEYWORDS = setOf(
			"abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
			"class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
			"enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
			"foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
			"long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
			"private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
			"sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
			"try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
			"void", "volatile", "while", "lock",
		)

		// Kotlin/JVM types (as surfaced by the reused JVM frontend) -> .NET equivalents.
		private val NET_TYPES = mapOf(
			"java.lang.Object" to "System.Object", "java.lang.String" to "System.String",
			"java.lang.Throwable" to "System.Exception", "kotlin.Throwable" to "System.Exception",
			"java.lang.Exception" to "System.Exception", "kotlin.Exception" to "System.Exception",
			"java.lang.RuntimeException" to "System.Exception", "kotlin.RuntimeException" to "System.Exception",
			"java.lang.ArithmeticException" to "System.ArithmeticException",
			"java.lang.IllegalArgumentException" to "System.ArgumentException",
			"kotlin.IllegalArgumentException" to "System.ArgumentException",
			"java.lang.IllegalStateException" to "System.InvalidOperationException",
			"kotlin.IllegalStateException" to "System.InvalidOperationException",
			"java.lang.IndexOutOfBoundsException" to "System.IndexOutOfRangeException",
			"java.lang.NullPointerException" to "System.NullReferenceException",
			"java.lang.UnsupportedOperationException" to "System.NotSupportedException",
		)
	}
}

private fun org.jetbrains.kotlin.ir.declarations.IrDeclaration.fqNameOrNull(): String? =
	(this as? IrSimpleFunction)?.let { fn ->
		val parent = fn.parent
		val parentFq = (parent as? org.jetbrains.kotlin.ir.declarations.IrPackageFragment)?.packageFqName?.asString()
		if (parentFq != null) "$parentFq.${fn.name.asString()}" else null
	}
